const powersData = [
  {
    Power: "Accuracy 1",
    FlavorText: "The character is an ace with ranged attacks.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character adds +1 to their Agility damage multiplier, and they gain a +1 bonus to Agility checks other than attacks.",
    Rank: 1
  },
  {
    Power: "Additional Limbs",
    FlavorText: "The character has extra limbs that can grab objects and attack foes.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character has an additional prehensile appendage (like a tail) or a symmetrical pair of them (like arms) that can be used to lift objects, use tools or otherwise take actions that normally require the use of a hand. This grants them an edge in Melee and Agility checks. A character can have as many additional limbs as they like—within reason—but they get no additional advantages for them.",
    Rank: 1
  },
  {
    Power: "Animal Bond",
    FlavorText: "The character can communicate with an animal friend.",
    PowerSet: "Telepathy",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character can communicate telepathically with one animal of their choice, and they must have befriended the animal before. They cannot switch to another animal unless the animal dies, but they can select this power multiple times if desired. The communication can be verbal, visual or even more complex, such as imparting location information. There is no limit to the distance of the communication, as long as the character and the animal are in the same dimension. Animals with a telepathic bond are generally willing to communicate, even if they aren't friendly. Bonded animals often do whatever the character asks, even if it might put them in danger.",
    Rank: 1
  },
  {
    Power: "Wish You Luck",
    FlavorText: "The character can make a friend lucky",
    PowerSet: "Luck",
    Prerequisites: "Lucky you, Rank 2",
    Action: "Standard",
    Trigger: "none",
    Duration: "Concentration",
    Range: "5 spaces per rank",
    Cost: 5,
    Effect: "The character picks an ally in line of sight. That ally gains an edge on all action checks made while this power is in effect. There is no limit on the range between the character and the ally once the power is activated. The character must pay the Focus cost at the start of each of their subsequent turns of concentration to keep the power working.",
    Rank: 2
  },
  {
    Power: "Animal Communication",
    FlavorText: "The character can communicate with a type of animal.",
    PowerSet: "Telepathy",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character can communicate telepathically with one taxonomic order of animals, such as birds, mammals, fish, amphibians and so on. They can call out to them as a group up to 500 spaces per rank away, and they can communicate specifically with ones they have met or at least seen. They cannot switch to another taxonomic order, but they can select this power multiple times if desired. The communication with the animals can be verbal, visual or even more complex, such as imparting location information. There is no limit to the distance of the communication, as long as the character and the animals are in the same dimension. Friendly animals often do whatever the character asks, as long as it doesn't put them in danger—and they may be willing to risk even that for one they consider a friend. Hostile animals simply ignore all such requests—which make them a poor choice for communication.",
    Rank: 1
  },
  {
    Power: "Attack Stance",
    FlavorText: "The character enters an aggressive attack stance, ready to strike in any direction.",
    PowerSet: "Martial Arts",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character doubles their Melee ability bonus to damage.",
    Rank: 1
  },
  {
    Power: "Banging Heads",
    FlavorText: "The character takes two nearby enemies and slams their heads into each other.",
    PowerSet: "Martial Arts",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes one Melee check against the Melee defense scores of two enemies within reach. If the attack fails against either foe, it fails entirely. If the attack is a success against both foes, each enemy takes full damage. On a fantastic Success, each enemy is also knocked prone.",
    Rank: 1
  },
  {
    Power: "Banging Heads",
    FlavorText: "The character takes two nearby enemies and slams their heads into each other.",
    PowerSet: "Super-Strength",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes one Melee check against the Melee defense scores of two enemies within reach. If the attack fails against either foe, it fails entirely. If the attack is a success against both foes, each enemy takes full damage. On a fantastic Success, each enemy is also knocked prone.",
    Rank: 1
  },
  {
    Power: "Blink",
    FlavorText: "The character teleports a short distance away.",
    PowerSet: "Teleportation",
    Prerequisites: "None",
    Action: "Standard/Movement/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character teleports into a clear space they can see or have been to, up to their rank in spaces away. If someone was about to attack them and they are now out of reach or line of sight, the attack automatically fails. If they are still within reach or line of sight, the attack has trouble instead.",
    Rank: 1
  },
  {
    Power: "Brawling",
    FlavorText: "The character has the moves and is hard to hit.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can use their Melee defense score against Agility attacks too.",
    Rank: 1
  },
  {
    Power: "Brilliance 1",
    FlavorText: "The character puts their brain to work.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character adds +1 to their Logic damage multiplier, and they gain a +1 bonus to Logic checks other than attacks.",
    Rank: 1
  },
  {
    Power: "Clobber",
    FlavorText: "The character pummels their foe with enough force to knock them flat.",
    PowerSet: "Super-Strength",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes a close attack against an enemy. If the attack is a success, the enemy takes regular damage. On a Fantastic success, the enemy takes double damage and is knocked prone.",
    Rank: 1
  },
  {
    Power: "Control Fog",
    FlavorText: "The character can create or dispel a thick fog.",
    PowerSet: "Weather Control",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character creates a thick fog for up to 50 spaces per rank around them that blocks all line of sight beyond 10 spaces. They can also dispel any fog in a similar area.",
    Rank: 1
  },
  {
    Power: "Copy Ability",
    FlavorText: "The character duplicates another character's ability.",
    PowerSet: "Power Control",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character picks one ability score of another character within 10 spaces and duplicates it. They now use that ability score in place of their own.",
    Rank: 1
  },
  {
    Power: "Copy Trait",
    FlavorText: "The character duplicates another character's trait.",
    PowerSet: "Power Control",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None", 
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character picks one trait another character within 10 spaces has and duplicates it. They can now use it as if it was always theirs.",
    Rank: 1
  },
  {
    Power: "Dampen Power",
    FlavorText: "The character tamps down another character's power.",
    PowerSet: "Power Control",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: "V",
    Effect: "The character picks one power from another character within 20 spaces and makes an Ego attack against them. On a success, they tamp the power down. If the power has ranges or effective areas or durations, these are halved. If the power affects a damage multiplier, subtract 1 from the effect. The power can no longer enjoy Fantastic successes. If the power has a Focus cost, the character must also pay that cost to dampen it.",
    Rank: 1
  },
  {
    Power: "Defense Stance",
    FlavorText: "The character enters a fluid defensive stance, hands poised to parry and counterattack.",
    PowerSet: "Martial Arts",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "Any close attacks made against the character have trouble until they are successfully attacked in this combat.",
    Rank: 1
  },
  {
    Power: "Discipline 1",
    FlavorText: "The character works to hone their power.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character adds +1 to their Ego damage multiplier, and they gain a +1 bonus to Ego checks other than attacks.",
    Rank: 1
  },
  {
    Power: "Disguise",
    FlavorText: "The character appears to be someone else.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character instantly alters their appearance so that they appear to be someone else. The target number for anyone trying to see through the disguise is the character's Ego defense. If the character is impersonating someone known to the other person, that person has an edge.",
    Rank: 1
  },
  {
    Power: "Double Tap",
    FlavorText: "To be twice as sure.",
    PowerSet: "Ranged weapons",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes a ranged attack against an enemy within 2 spaces. If the attack is a success, the enemy takes regular damage. On a Fantastic success, the enemy takes double damage and is bleeding.",
    Rank: 1
  },
  {
    Power: "Elemental Burst",
    FlavorText: "The character fires a burst of their element.",
    PowerSet: "Elemental Control",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "10",
    Cost: 0,
    Effect: "The character makes a ranged attack against an enemy in line of sight. If the attack is a success, it inflicts regular damage. On a Fantastic success, the enemy takes double damage instead and the elemental type’s special effect.",
    Rank: 1
  },
  {
    Power: "Environmental Protection",
    FlavorText: "Environmental effects don't bother the character.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character is not harmed by intense cold or heat, the pressure of the deep seas or the intense radiation and vacuum of space. The player can choose any or all of these protections, as best fits with the character concept.",
    Rank: 1
  },
  {
    Power: "ESP",
    FlavorText: "The character can sense the presence of others.",
    PowerSet: "Telepathy",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character can reach out with their mind to sense the presence of others within 100 spaces per rank. This tells them the person’s location and general status. It can also identify if they have super-powers or not. If a target or targets wish to remain undetected, the character must make a Logic check and compare it against each target's Vigilance defense. If they succeed, they sense the target. On a Fantastic success, they can also identify the source of any powers the target has.",
    Rank: 1
  },
  {
    Power: "Evasion",
    FlavorText: "The character can dodge fists quickly.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can use their Agility defense score against Melee attacks too.",
    Rank: 1
  },
  {
    Power: "Extended Reach 1",
    FlavorText: "The character's reach grows.",
    PowerSet: "Plasticity",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character's reach quadruples.",
    Rank: 1
  },
  {
    Power: "Fast Attacks",
    FlavorText: "The character's weapons lash out!",
    PowerSet: "Melee Weapons",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character splits their attack to make two close attacks against separate targets within reach (or they can focus a single attack on a single target). Make a single Melee check and compare it to the targets’ Melee defenses. On a success, the affected target takes half regular damage. On a Fantastic success, the affected target takes full damage, and the character can make a bonus attack with this power against any target within reach, with the same effect.",
    Rank: 1
  },
  {
    Power: "Fast Strikes",
    FlavorText: "The character unleashes a flurry of strikes.",
    PowerSet: "Martial Arts",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character splits their attack to make two close attacks against separate targets within reach (or they can focus a single attack on a single target). Make a single Melee check and compare it to the targets’ Melee defenses. On a success, the affected target takes half regular damage. On a Fantastic success, the affected target takes full damage.",
    Rank: 1
  },
  {
    Power: "Flexible Bones 1",
    FlavorText: "The character's skeleton is rubbery.",
    PowerSet: "Plasticity",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character gains Health Damage Reduction 1. They also have an edge on Agility checks for contortion and escape.",
    Rank: 1
  },
  {
    Power: "Flexible Fingers",
    FlavorText: "The character can turn their fingers and hands into whatever tool they need.",
    PowerSet: "Plasticity",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "With a standard action, the character can automatically pick any lock that requires a physical key. They can also shape their hands to form almost any other kind of simple tool.",
    Rank: 1
  },
  {
    Power: "Grow 1",
    FlavorText: "The character sizes up!",
    PowerSet: "Resize",
    Prerequisites: "None",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can grow up to huge size. They can return to their normal size at will.",
    Rank: 1
  },
  {
    Power: "Grow 2",
    FlavorText: "The character becomes even bigger!",
    PowerSet: "Resize",
    Prerequisites: "Grow 1",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can grow up to gigantic size. They can return to their normal size at will.",
    Rank: 1
  },
  {
    Power: "Grow 3",
    FlavorText: "The character can be the size of a house!",
    PowerSet: "Resize",
    Prerequisites: "Grow 2",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can grow up to titanic size. They can return to their normal size at will.",
    Rank: 1
  },
  {
    Power: "Grow 4",
    FlavorText: "The character can tackle kaiju!",
    PowerSet: "Resize",
    Prerequisites: "Grow 3",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can grow up to gargantuan size. They can return to their normal size at will.",
    Rank: 1
  },
  {
    Power: "Healing Factor",
    FlavorText: "The character heals amazingly fast.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "At the end of the character's turn, they regain Health equal to their Resilience. (This works outside of combat too, quickly bringing them back to full Health.)",
    Rank: 1
  },
  {
    Power: "Heightened Senses 1",
    FlavorText: "The character has superior senses.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can sense things roughly twice as far away as normal. They also have an edge on Vigilance checks to perceive things, and enemies have trouble on checks they make to sneak past the character.",
    Rank: 1
  },
  {
    Power: "Heightened Senses 2",
    FlavorText: "The character has senses as sharp as radar.",
    PowerSet: "None",
    Prerequisites: "Heightened Senses 1",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can sense things roughly four times as far away as normal. They also have an edge on Vigilance checks to perceive things, and enemies have trouble on checks they make to sneak past the character.",
    Rank: 2
  },
  {
    Power: "Hit & Run",
    FlavorText: "The character hits hard and keeps moving!",
    PowerSet: "Melee Weapons",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes a close attack with an edge on an enemy. If the attack is a success, the enemy takes regular damage, and the character can make an additional movement up to half their Run Speed for free. On a Fantastic success, the enemy takes double damage and suffers the weapon's special effect.",
    Rank: 1
  },
  {
    Power: "Iconic Weapon",
    FlavorText: "Better keep this handy",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character is known for owning and using a unique and powerful weapon, like Mjolnir (Thor's hammer) or Captain America’s shield. The Narrator must approve the details of this weapon. This power can be taken more than once, but each time must be with a different weapon.",
    Rank: 1
  },
  {
    Power: "Illumination",
    FlavorText: "The character creates a bright light.",
    PowerSet: "Illusion",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character illuminates one object or point in line of sight, within 50 spaces, with bright light. The character can maintain concentration on the effect even if they move out of range or line of sight.",
    Rank: 1
  },
  {
    Power: "Immovable",
    FlavorText: "Nobody pushes the character around.",
    PowerSet: "Shield Bearer",
    Prerequisites: "None",
    Action: "Reaction",
    Trigger: "The character is knocked back or knocked prone.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "For every point of Melee defense the character has, they can reduce knockback by 1 space.",
    Rank: 1
  },
  {
    Power: "Immovable",
    FlavorText: "Nobody pushes the character around.",
    PowerSet: "Super-Strength",
    Prerequisites: "None",
    Action: "Reaction",
    Trigger: "The character is knocked back or knocked prone.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "For every point of Melee defense the character has, they can reduce knockback by 1 space.",
    Rank: 1
  },
  {
    Power: "Inspiration",
    FlavorText: "The character's words inspire their allies.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "1 Round",
    Range: "None",
    Cost: 0,
    Effect: "The character inspires an ally in earshot. The ally gains an edge on all action checks until the start of the character's next turn.",
    Rank: 1
  },
  {
    Power: "Integrity",
    FlavorText: "The character can think their way through.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can use their Logic defense score against Ego attacks too.",
    Rank: 1
  },
  {
    Power: "Keep Moving",
    FlavorText: "The character can keep allies moving under fire.",
    PowerSet: "Tactics",
    Prerequisites: "None",
    Action: "Reaction",
    Trigger: "An ally in line of sight and earshot is demoralized or stunned.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The demoralized or stunned condition ends.",
    Rank: 1
  },
  {
    Power: "Levitation",
    FlavorText: "The character can hover and move.",
    PowerSet: "Telekinesis",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can move through the air in any direction at their Run Speed.",
    Rank: 1
  },
  {
    Power: "Machine Telepathy",
    FlavorText: "The character can communicate with machines with their mind.",
    PowerSet: "Telepathy",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character can communicate telepathically with one machine at a time, and they must have seen the machine before. The communication can be verbal, visual or even more complex, such as imparting location information. There is no limit to the distance of the communication, as long as the character and the machine are in the same dimension. Simple machines do not have much to offer in the way of conversation, but they are also generally compliant with requests. Complex machines—like computers, smartphones and other electronics—are also often compliant, but if they are secured in any way, they usually refuse to communicate with strangers. A Logic check can get the character past such security, and the Narrator should set the target number according to the strength of the security.",
    Rank: 1
  },
  {
    Power: "Mental Punch",
    FlavorText: "The character can blast a foe’s mind in melee.",
    PowerSet: "Telepathy",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes a Melee attack against a target. If the attack is a success, it inflicts regular Focus damage (instead of Health damage). On a Fantastic success, the target takes double damage instead and is stunned for one round.",
    Rank: 1
  },
  {
    Power: "Mighty 1",
    FlavorText: "The character is superhumanly strong.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "Treat the character as one size bigger for lifting, carrying, swinging and throwing things. They also add +1 to their Melee damage multiplier, and they gain a +1 bonus to Melee checks other than attacks.",
    Rank: 1
  },
  {
    Power: "Mind Reading",
    FlavorText: "The character can read thoughts.",
    PowerSet: "Telepathy",
    Prerequisites: "Telepathic Link",
    Action: "Standard",
    Trigger: "None",
    Duration: "1 Round",
    Range: "None",
    Cost: 0,
    Effect: "The character can read the thoughts of a single person with whom they have established a Telepathic Link. This requires a Logic check against the target's Logic defense. On a success, the character can read the target's surface thoughts. On a Fantastic success, the character can ask a single simple question and get the answer from the target's mind.",
    Rank: 1
  },
  {
    Power: "Penance Stare",
    FlavorText: "The character can punish the wicked with their gaze.",
    PowerSet: "Magic",
    Prerequisites: "Cursed",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 5,
    Effect: "The character makes an Ego attack against a target character within 3 spaces per rank. If it’s a success, the target takes Focus damage. On a Fantastic success, the target takes double damage and is paralyzed for one round. Characters with the Heroic tag take half the listed damage from this power in either case. If a target is shattered by this power, they can recover, but they come back in one of two ways. Either they are cleansed of their sins and ready to make a new start with a clean slate, or their emotions are drained from them permanently. How this works in each case is up to the Narrator.",
    Rank: 1
  },
  {
    Power: "Phase Self",
    FlavorText: "The character can become as intangible as a ghost.",
    PowerSet: "Phasing",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character (and their clothing) becomes intangible and can move through anything as if it wasn't there. Nothing can physically affect them, nor can they affect anything else that is not phasing along with them.",
    Rank: 1
  },
  {
    Power: "Reinforced Skeleton",
    FlavorText: "The character has a skeleton replaced or covered in some material.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character gains health reduction 1.",
    Rank: 1
  },
  {
    Power: "Riposte",
    FlavorText: "Seeing the enemy is off balance the character strikes back.",
    PowerSet: "Melee Weapons",
    Prerequisites: "None",
    Action: "Reaction",
    Trigger: "An enemy makes a close attack against the character that fails.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes a close attack on an enemy who just missed them. If the attack is a success, the enemy takes normal damage. On a Fantastic success, the enemy takes double damage and suffers the weapons special effect.",
    Rank: 1
  },
  {
    Power: "Rubber Neck",
    FlavorText: "The character can lengthen and twist their neck.",
    PowerSet: "Plasticity",
    Prerequisites: "Flexible Bones 1, Extended Reach 1",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can move their head away from their body, up to their reach, to establish a line of sight to a target.",
    Rank: 1
  },
  {
    Power: "Sense Sins",
    FlavorText: "The character can look into a person’s soul.",
    PowerSet: "Magic",
    Prerequisites: "Cursed",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character can sense the sins of a target within 10 spaces. This requires an Ego check against the target's Ego defense. On a success, the character learns the target's greatest sin. On a Fantastic success, the character learns all of the target's sins.",
    Rank: 1
  },
  {
    Power: "Sense Supernatural",
    FlavorText: "The character can sense the supernatural.",
    PowerSet: "Magic",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character can reach out with their mind to sense the presence of supernatural people, places or things within 100 spaces per rank. This tells them the location of the supernatural thing and its general status. If a target or targets wish to remain undetected, the character must make an Ego check and compare it against each target's Vigilance defense. If they succeed, they sense the target. On a Fantastic success, they can also identify if the target is cursed or demonic.",
    Rank: 1
  },
  {
    Power: "Shield 1",
    FlavorText: "The character wields a personal shield.",
    PowerSet: "Shield Bearer",
    Prerequisites: "None",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character gains Health Damage Reduction 1.",
    Rank: 1
  },
  {
    Power: "Shield Bash",
    FlavorText: "The character bashes a foe with their shield.",
    PowerSet: "Shield Bearer",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes a close attack on an enemy within their reach. If the attack is a success, the enemy takes regular damage. On a Fantastic success, the enemy takes double damage and is knocked prone.",
    Rank: 1
  },
  {
    Power: "Shield Deflection",
    FlavorText: "The character uses their shield to deflect attacks.",
    PowerSet: "Shield Bearer",
    Prerequisites: "None",
    Action: "Reaction",
    Trigger: "The character is the target of an attack against their Agility defense.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The attack has trouble.",
    Rank: 1
  },
  {
    Power: "Shrink 1",
    FlavorText: "The character thinks small.",
    PowerSet: "Resize",
    Prerequisites: "None",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can shrink down to little size. They can return to their normal size at will.",
    Rank: 1
  },
  {
    Power: "Shrink 2",
    FlavorText: "The character becomes even smaller!",
    PowerSet: "Resize",
    Prerequisites: "Shrink 1",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can shrink down to tiny size. They can return to their normal size at will.",
    Rank: 1
  },
  {
    Power: "Shrink 3",
    FlavorText: "The character is smaller than an action figure.",
    PowerSet: "Resize",
    Prerequisites: "Shrink 2",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can shrink down to miniature size. They can return to their normal size at will.",
    Rank: 1
  },
  {
    Power: "Shrink 4",
    FlavorText: "The character is so small that they're hard to see.",
    PowerSet: "Resize",
    Prerequisites: "Shrink 3",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can shrink down to microscopic size. They can return to their normal size at will.",
    Rank: 1
  },
  {
    Power: "Slip Free",
    FlavorText: "The character is impossible to restrain.",
    PowerSet: "Plasticity",
    Prerequisites: "None",
    Action: "Reaction",
    Trigger: "The character is grabbed or pinned.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character is not grabbed or pinned.",
    Rank: 1
  },
  {
    Power: "Slow-Motion Dodge",
    FlavorText: "Time seems to slow down for the character, making it easy to dodge enemy attacks.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "Reaction",
    Trigger: "An enemy makes an attack against the character's Agility defense.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The enemy has trouble on the attack.",
    Rank: 1
  },
  {
    Power: "Snap Shooting",
    FlavorText: "The character shoots from the hip with deadly speed.",
    PowerSet: "Ranged weapons",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character splits their attack to make two ranged attacks against separate targets (or they can focus a single attack on a single target). Make a single Agility check and compare it to the targets’ Agility defenses. On a success, an affected target takes half regular damage. On a Fantastic success, an affected target takes full damage and is bleeding.",
    Rank: 1
  },
  {
    Power: "Spider-Dodge",
    FlavorText: "The character dodges attacks with a spider-like scuttle.",
    PowerSet: "Spider-Powers",
    Prerequisites: "None",
    Action: "Reaction",
    Trigger: "Someone makes an Agility attack against the character.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The attacker has trouble on the attack. If the attack misses, the character can leap in any direction at their Jump Speed.",
    Rank: 1
  },
  {
    Power: "Spider-Pheromones",
    FlavorText: "The character exudes pheromones that affect those nearby.",
    PowerSet: "Spider-Powers",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 5,
    Effect: "The character has an edge on Ego (intimidation) checks against people who are not attracted to their gender. They also have an edge on Ego (persuasion) checks against people who are attracted to their gender.",
    Rank: 1
  },
  {
    Power: "Spider-Sense",
    FlavorText: "The character has a sense of danger that tingles when threats are near.",
    PowerSet: "Spider-Powers",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character has an edge on initiative checks and on Vigilance checks to perceive danger. Enemies have trouble on Agility checks against the character's Vigilance defense. The character also gains a permanent +2 bonus to their Agility defense.",
    Rank: 1
  },
  {
    Power: "Spider-Strike",
    FlavorText: "The character strikes in a blur of punches, kicks and webbing.",
    PowerSet: "Spider-Powers",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character splits their attack to make two close attacks against separate targets within reach (or they can focus a single attack on a single target). Make a single Melee check and compare it to the targets’ Melee defenses. On a success, the affected target takes half regular damage. On a Fantastic success, the affected target takes full damage and is paralyzed by webbing. Breaking free from webbing requires a Melee check (target number 20). After the attacks, the character may run, jump or climb at half speed for free.",
    Rank: 1
  },
  {
    Power: "Static Illusion",
    FlavorText: "By manipulating visual light, the character creates a realistic hologram.",
    PowerSet: "Illusion",
    Prerequisites: "Illumination",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character creates a visual-only illusion anywhere in line of sight, within 50 spaces. The illusion can be of anything up to three sizes larger than the character, but it must be static. The character breaks concentration if they move beyond 50 spaces from the illusion or lose line of sight of it.",
    Rank: 1
  },
  {
    Power: "Sturdy 1",
    FlavorText: "The character has protection from physical damage.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character's body is so sturdy that they have Health Damage Reduction 1. If this power stems from armor or anything else removable—like Iron Man’s armor—the character should apply the Tech Reliance trait to it.",
    Rank: 1
  },
  {
    Power: "Suppressive Fire",
    FlavorText: "The character forces their foes to keep their heads down.",
    PowerSet: "Ranged weapons",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes an Agility attack against a target's Vigilance defense. If the attack is a success, apply Health Damage Reduction normally. Any damage taken is then applied to the target's Focus instead. If it’s a Fantastic success, the damage is doubled, and if the target takes any Focus damage, they are stunned for one round.",
    Rank: 1
  },
  {
    Power: "Telekinetic Manipulation",
    FlavorText: "The character can handle physical things with their mind.",
    PowerSet: "Telekinesis",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "V",
    Cost: 0,
    Effect: "The character can manipulate objects in their line of sight with their mind. The maximum range for this is 5 spaces times the character's rank. If someone tries to prevent the character from taking control of an object, the character makes a Logic check against the opponent's Agility defense.",
    Rank: 1
  },
  {
    Power: "Telepathic Link",
    FlavorText: "The character can speak with another telepathically.",
    PowerSet: "Telepathy",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The character can communicate telepathically with one person at a time, and they must have met or seen the other person before. The communication can be verbal, visual or even more complex, such as imparting location information. There is no limit to the distance of the communication, as long as the character and the target are in the same dimension. If the other person does not wish to speak with the character, the target can automatically tune them out. To force a telepathic link, the character can make a Logic check against the target's Vigilance defense. On a failure, the character cannot attempt to communicate with the target in this way for the rest of the day. On a success, the character can communicate with the target for one round. On a Fantastic success, the target cannot shut the character out for the rest of the day.",
    Rank: 1
  },
  {
    Power: "Teleport 1",
    FlavorText: "The character teleports someplace else.",
    PowerSet: "Teleportation",
    Prerequisites: "Blink",
    Action: "Standard/Movement",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character teleports into a clear space they can see or have been to, up to 10 times their rank in spaces away. Outside of combat, they can teleport up to 100 times their rank in spaces away.",
    Rank: 1
  },
  {
    Power: "Teleport 2",
    FlavorText: "The character teleports great distances.",
    PowerSet: "Teleportation",
    Prerequisites: "Teleport 1",
    Action: "Standard/Movement",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "Outside of combat, the character can teleport up to 1,000 times their rank in spaces away.",
    Rank: 1
  },
  {
    Power: "Thunder",
    FlavorText: "The character causes a deafening crack of thunder.",
    PowerSet: "Weather Control",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes an Ego check and compares that against the Resilience defense of every character within 10 spaces. Any character the attack succeeds against is deafened. On a Fantastic success, the character is also stunned for one round.",
    Rank: 1
  },
  {
    Power: "Uncanny 1",
    FlavorText: "The character has protection against mental assaults.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "Any damage multiplier for attacks against the character's Focus is reduced by 1. If this power is part of a battle suit, the power is integrated into a removable helmet. Otherwise, it’s a part of the character. If this power stems from armor or anything else removable—like Magneto's helmet—the character should apply the Tech Reliance trait to it.",
    Rank: 1
  },
  {
    Power: "Venom Blast",
    FlavorText: "The character unleashes a bioelectric shock.",
    PowerSet: "Spider-Powers",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "5",
    Cost: 0,
    Effect: "The character makes a ranged attack. If the attack is a success, it does regular damage. On a Fantastic success, the attack does double damage, and if the target suffers any actual damage, they are also stunned for one round.",
    Rank: 1
  },
  {
    Power: "Vicious Attack",
    FlavorText: "The character strikes a felling blow.",
    PowerSet: "Melee Weapons",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character makes a close attack. If the attack is a success, the enemy takes regular damage. On a Fantastic success, the enemy takes double damage and suffers the weapon's special effect.",
    Rank: 1
  },
  {
    Power: "Wall Crawling",
    FlavorText: "The character can climb like a spider.",
    PowerSet: "Spider-Powers",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can climb at a speed equal to their regular speed. Under normal conditions, they never lose their grip, no matter the angle of the surface.",
    Rank: 1
  },
  {
    Power: "Weapons Blazing",
    FlavorText: "The character blazes two foes at once",
    PowerSet: "Ranged weapons",
    Prerequisites: "Snap Shooting",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character splits their attack to make two ranged attacks against separate targets (or they can focus a single attack on a single target) Make a single Agility check and compare it to the targets’ Agility defenses. On a success, the affected target takes half regular damage. On a Fantastic success, the affected target takes full damage, and the character can make a bonus attack with this power against any available target with the same effect",
    Rank: 1
  },
  {
    Power: "Weather Chill",
    FlavorText: "The character cools things down",
    PowerSet: "Weather Control",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The temperature in an area roughly a mile across falls as low as 0 degrees Fahrenheit.",
    Rank: 1
  },
  {
    Power: "Weather Warm",
    FlavorText: "The character heats things up",
    PowerSet: "Weather Control",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "The temperature in an area roughly a mile across rises as high as 100 degrees Fahrenheit.",
    Rank: 1
  },
  {
    Power: "Webcasting",
    FlavorText: "The character can snare a target in a web",
    PowerSet: "Spider-Powers",
    Prerequisites: "None",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 10,
    Effect: "The character makes a ranged attack on an enemy If the attack is a success, the web paralyzes the enemy. On a Fantastic success, the enemy is also pinned. Breaking free from webbing requires a Melee check (target number 20).",
    Rank: 1
  },
  {
    Power: "Wisdom",
    FlavorText: "The character not only has brains, but knows how to use them.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character can use their Ego defense score against Logic attacks too.",
    Rank: 1
  },
  {
    Power: "Wisecracker",
    FlavorText: "The character irritates the foe with sharp wit.",
    PowerSet: "None",
    Prerequisites: "None",
    Action: "Reaction",
    Trigger: "The character succeeds an attack against an enemy in earshot, or an enemy within earshot fails an attack on them.",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character cracks a joke at the enemy's expense. Make an Ego attack. On a success do regular focus damage. On a Fantastic Success the damage is doubled and the target is stunned for one round.",
    Rank: 1
  },
  {
    Power: "Accuracy 2",
    FlavorText: "The character is a sharpshooter.",
    PowerSet: "None",
    Prerequisites: "Accuracy 1, Rank 2",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character adds +2 to their Agility damage multiplier, and they gain a +2 bonus to Ability checks other than attacks.",
    Rank: 2
  },
  {
    Power: "Animated Illusion",
    FlavorText: "By manipulating visual light, the character creates a moving hologram.",
    PowerSet: "Illusion",
    Prerequisites: "Static Illusion, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character creates a visual-only illusion anywhere in line of sight, within 50 spaces. The illusion can be anything up to four sizes larger than the character,and it can move freely within its limits. The character breaks concentration if they move beyond 50 spaces from the illusion or lose line of sight to it.",
    Rank: 2
  },
  {
    Power: "Astral Form",
    FlavorText: "The character can enter the Astral Plane.",
    PowerSet: "Magic",
    Prerequisites: "Sorcerous, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character can project an avatar into the Astral Plane, leaving their physical body in a deep trance in the real world, where it is vulnerable to attack. While in the Astral Plane, they can interact with other characters in the Astral Plane, but they are intangible, invisible and generally undetectable in the real world. However, they can sense things in the real world. If the character is Rank 4 or higher, they can also take on a transparent form that can be seen in the real world.While in the Astral Plane, the character can fly, and in combat, their Flight Speed is equal to their rank times their Run Speed. Outside of combat, they can move 10 times as fast.",
    Rank: 2
  },
  {
    Power: "Battle Plan",
    FlavorText: "The character always has a plan.",
    PowerSet: "Tactics",
    Prerequisites: "Inspiration, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "1 Round",
    Range: "None",
    Cost: 10,
    Effect: "The character inspires one or more allies of their choice in earshot, up to the character's Vigilance. Inspired Allies gain an edge on all action checks until the start of the character's next turn.",
    Rank: 2
  },
  {
    Power: "Blazing-Fast Fists",
    FlavorText: "The character can attack superfast.",
    PowerSet: "Super-Speed",
    Prerequisites: "Rank 2",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character has an edge on all Melee attacks.",
    Rank: 2
  },
  {
    Power: "Blink Barrage",
    FlavorText: "The character teleports rapidly around an opponent.",
    PowerSet: "Teleportation",
    Prerequisites: "Blink, Rank 2",
    Action: "Standard/Movement",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 0,
    Effect: "The character teleports several times in quick succession and winds up in a clear space they can see or have been to, up to their rank in spaces away. Any attacks have trouble against them for one round.",
    Rank: 2
  },
  {
    Power: "Blur",
    FlavorText: "The character moves like a blur!",
    PowerSet: "Super-Speed",
    Prerequisites: "Speed Run 2, Rank 2",
    Action: "Standard/Reaction",
    Trigger: "The character is attacked.",
    Duration: "1 Round",
    Range: "None",
    Cost: 5,
    Effect: "Any attacks against the character have trouble.",
    Rank: 2
  },
  {
    Power: "Bolts of Balthakk",
    FlavorText: "The character fires enchanted bolts of electricity from their fingers.",
    PowerSet: "Magic",
    Prerequisites: "Sorcerous, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "20",
    Cost: 5,
    Effect: "The character makes an Ego check with an edge against the Agility defense of a target in their line of sight. For this attack, add +1 to the character's Agility Damage bonus for every 2 points of Focus they spend. On a success, an affected target takes that total damage. On a Fantastic success, an affected target takes double that total damage and is stunned for one round.",
    Rank: 2
  },
  {
    Power: "Borrow Senses",
    FlavorText: "The character can use another person's senses.",
    PowerSet: "Telepathy",
    Prerequisites: "Telepathic Link, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character can use the full senses of someone or something with whom they have established a telepathic link or bond. While they do, they retain the use of their own senses too.",
    Rank: 2
  },
  {
    Power: "Bounce Back",
    FlavorText: "The character bounces back from even the hardest falls.",
    PowerSet: "Plasticity",
    Prerequisites: "Flexible Bones 1, Slip Free, Rank 2",
    Action: "Reaction",
    Trigger: "The character takes damage from a fall or is knocked prone.",
    Duration: "Instant",
    Range: "None",
    Cost: 5,
    Effect: "The fall doesn't damage the character. If they're prone, they stand up. If they'd like, they can also jump a number of spaces, up to their Run Speed.",
    Rank: 2
  },
  {
    Power: "Brace for Impact",
    FlavorText: "The character mentally toughens themselves for a fight.",
    PowerSet: "Martial Arts",
    Prerequisites: "Do This All Day, Rank 2",
    Action: "Reaction",
    Trigger: "An enemy deals physical damage to the character.",
    Duration: "Instant",
    Range: "None",
    Cost: 5,
    Effect: "For every point of Focus spent, the character can ignore 1 point of Health damage dealt by the attack.",
    Rank: 2
  },
  {
    Power: "Brain Drain",
    FlavorText: "The character consumes the energies of another.",
    PowerSet: "Magic",
    Prerequisites: "Rank 2",
    Action: "Reaction",
    Trigger: "The target is grabbed.",
    Duration: "Instant",
    Range: "None",
    Cost: 5,
    Effect: "The character makes an Ego attack against the target's Vigilance. If it succeeds, the target takes regular Focus damage, and the character heals half that much Focus for themselves. On a Fantastic success, the character heals their full Focus damage instead.",
    Rank: 2
  },
  {
    Power: "Brilliance 2",
    FlavorText: "Everything makes more sense to the character.",
    PowerSet: "None",
    Prerequisites: "Brilliance 1, Rank 2",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character adds +2 to their Logic damage multiplier, and they gain a +2 bonus to Logic checks other than attacks.",
    Rank: 2
  },
  {
    Power: "Bump Power",
    FlavorText: "The character bumps up another character's power.",
    PowerSet: "Power Control",
    Prerequisites: "Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character picks one power from another character within 5 spaces and boosts it. If the power has ranges or effective areas or durations, these are doubled. If the power affects a damage multiplier, add 1 to the effect. Any effects that normally happen with a Fantastic Success automatically happen on any success, not just a Fantastic one. If the power has a cost, the character must pay it as well, with a minimum of 5 Focus.",
    Rank: 2
  },
  {
    Power: "Chain Strikes",
    FlavorText: "The character unleashes a hail of strikes.",
    PowerSet: "Martial Arts",
    Prerequisites: "Fast Strikes, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 5,
    Effect: "The character makes a close attack with an edge. If The attack is a success, the enemy takes regular damage. On a Fantastic success, the character can also make an additional Chain Strike.",
    Rank: 2
  },
  {
    Power: "Change of Plans",
    FlavorText: "The character thinks of a better way.",
    PowerSet: "Tactics",
    Prerequisites: "Inspiration, Rank 2",
    Action: "Reaction",
    Trigger: "An ally has trouble on an action check.",
    Duration: "1 Round",
    Range: "None",
    Cost: 5,
    Effect: "The ally gains an edge on that action check.",
    Rank: 2
  },
  {
    Power: "Cloak",
    FlavorText: "The character makes people believe they're not there.",
    PowerSet: "Telepathy",
    Prerequisites: "Telepathic Link, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character uses a mirage to block their presence from the minds of people within 20 spaces per rank. Cameras (for instance) can still record them, but when people look in the character's direction, they see nothing there. The target number for anyone trying to detect the character is the character's Logic defense.",
    Rank: 2
  },
  {
    Power: "Clone Moves",
    FlavorText: "The character duplicates another character's combat moves.",
    PowerSet: "Power Control",
    Prerequisites: "Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character picks another character within 10 spaces and in their line of sight and duplicates all their powers that could be selected with the Special Training Origin. They can now use those powers as if they were always there. If the copied powers have costs, the character must pay the highest of them, or a minimum of 5 Focus.",
    Rank: 2
  },
  {
    Power: "Combat Trickery",
    FlavorText: "The character is a tricky one!",
    PowerSet: "None",
    Prerequisites: "Rank 2",
    Action: "Reaction",
    Trigger: "The character makes an attack.",
    Duration: "Instant",
    Range: "None",
    Cost: 5,
    Effect: "Once per battle, when the character is attacking targets of equal or higher rank, the character automatically rolls a 1 on their Marvel die, and that die cannot be affected by trouble. If the character is attacking multiple targets, all the targets must be of equal or higher rank.",
    Rank: 2
  },
  {
    Power: "Command",
    FlavorText: "The character forces someone to follow an order.",
    PowerSet: "Telepathy",
    Prerequisites: "Telepathic Link, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "1 Round",
    Range: "None",
    Cost: 5,
    Effect: "The character gives an order to a target with whom they've established a Telepathic Link. The character makes a Logic check against the target’s Logic defense. On a success, the target complies with the order. On a Fantastic success, the character gains an edge the next time they use this power against this same target. The command must be something that can be completed in a single action. If it involves harming someone, the character has trouble on the check. If it would cause the target to harm themselves, the character has double trouble on the check.",
    Rank: 2
  },
  {
    Power: "Control Weather 1",
    FlavorText: "The character can make it rain.",
    PowerSet: "Weather Control",
    Prerequisites: "Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 0,
    Effect: "It starts to rain in an area up to 5 miles across times the character's rank, centered on the character. All Ranges are cut in half. Movement is not affected.",
    Rank: 2
  },
  {
    Power: "Copy Power",
    FlavorText: "The character duplicates another character's power.",
    PowerSet: "Power Control",
    Prerequisites: "Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character picks one power a target within 10 spaces has and duplicates it. They can now use it as if it was always theirs. If the copied power has a cost, the character must pay it as well, with a minimum of 5 Focus.",
    Rank: 2
  },
  {
    Power: "Create Illusion",
    FlavorText: "The character creates a realistic illusion.",
    PowerSet: "Illusion",
    Prerequisites: "Static Illusion, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character creates a visual-only illusion anywhere in line of sight, within 50 spaces. The illusion can be anything up to four sizes larger than the character, and it can move freely within its limits. The character breaks concentration if they move beyond 50 spaces from the illusion or lose line of sight to it.",
    Rank: 2
  },
  {
    Power: "Danger Sense",
    FlavorText: "The character has a heightened sense of danger.",
    PowerSet: "None",
    Prerequisites: "Rank 2",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character has an edge on initiative checks and on Vigilance checks to perceive danger. Enemies have trouble on Agility checks against the character's Vigilance defense.",
    Rank: 2
  },
  {
    Power: "Defensive Stance",
    FlavorText: "The character enters a defensive stance.",
    PowerSet: "Martial Arts",
    Prerequisites: "Defense Stance, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "Any close attacks made against the character have trouble until they are successfully attacked in this combat.",
    Rank: 2
  },
  {
    Power: "Discipline 2",
    FlavorText: "The character hones their power further.",
    PowerSet: "None",
    Prerequisites: "Discipline 1, Rank 2",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character adds +2 to their Ego damage multiplier, and they gain a +2 bonus to Ego checks other than attacks.",
    Rank: 2
  },
  {
    Power: "Disguise Self",
    FlavorText: "The character can disguise themselves as someone else.",
    PowerSet: "None",
    Prerequisites: "Disguise, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 5,
    Effect: "The character instantly alters their appearance so that they appear to be someone else. The target number for anyone trying to see through the disguise is the character's Ego defense. If the character is impersonating someone known to the other person, that person has an edge.",
    Rank: 2
  },
  {
    Power: "Double Strike",
    FlavorText: "The character strikes twice in quick succession.",
    PowerSet: "Melee Weapons",
    Prerequisites: "Fast Attacks, Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Instant",
    Range: "None",
    Cost: 5,
    Effect: "The character makes two close attacks against separate targets within reach (or they can focus a single attack on a single target). Make a single Melee check and compare it to the targets’ Melee defenses. On a success, the affected target takes half regular damage. On a Fantastic success, the affected target takes full damage, and the character can make a bonus attack with this power against any target within reach, with the same effect.",
    Rank: 2
  },
  {
    Power: "Elemental Control 1",
    FlavorText: "The character can control an element.",
    PowerSet: "Elemental Control",
    Prerequisites: "Rank 2",
    Action: "Standard",
    Trigger: "None",
    Duration: "Concentration",
    Range: "None",
    Cost: 5,
    Effect: "The character can control an element within 50 spaces. They can move it, shape it, and use it to attack. The character makes a ranged attack against an enemy in line of sight. If the attack is a success, it inflicts regular damage. On a Fantastic success, the enemy takes double damage instead and the elemental type’s special effect.",
    Rank: 2
  },
  {
    Power: "Enhanced Reflexes",
    FlavorText: "The character has enhanced reflexes.",
    PowerSet: "None",
    Prerequisites: "Rank 2",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character has an edge on Agility checks and on Agility defense.",
    Rank: 2
  },
  {
    Power: "Extended Reach 2",
    FlavorText: "The character's reach extends even further.",
    PowerSet: "Plasticity",
    Prerequisites: "Extended Reach 1, Rank 2",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character's reach is doubled again.",
    Rank: 2
  },
  {
    Power: "Fast Healing",
    FlavorText: "The character heals quickly.",
    PowerSet: "None",
    Prerequisites: "Healing Factor, Rank 2",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "At the end of the character's turn, they regain Health equal to twice their Resilience. (This works outside of combat too, quickly bringing them back to full Health.)",
    Rank: 2
  },
  {
    Power: "Flexible Bones 2",
    FlavorText: "The character's skeleton is even more rubbery.",
    PowerSet: "Plasticity",
    Prerequisites: "Flexible Bones 1, Rank 2",
    Action: "None",
    Trigger: "None",
    Duration: "Permanent",
    Range: "None",
    Cost: 0,
    Effect: "The character gains Health Damage Reduction 2. They also have an edge on Agility checks for contortion and escape.",
    Rank: 2
  },
]